### ISSUE TITLE
Auto Restart Problem 

### ISSUE THREAD

**Issue by venkateshv1266** [Evolution-XYZ-Devices/device_xiaomi_ginkgo#2]
Previously I was using PE+ rom. Recently I have changed my rom to EvoX rom. Now I'm facing an issue of auto restart while using the phone. When I get a notification or when I play a video or when I get an incoming call, my phone automatically restarts. Please fix this issue.

**Comment by tejas101k** [comment]
Any further logcat which could precisely address your spot on issue would be needed. As it could be even one of your device's deprecating hardware asset life (generally battery) causing this, which I have mostly seen as common causes that are in the conduct of issue you have described. As other users including me are sheltered from this...


* Also make sure before submitting the logcat

- You must be on stock provided kernel
- No conflicting magisk module or any other suspicious systemless mods should be interfering
